steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/stoked-castle-409104/game-of-thrones-personality-matcher', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/stoked-castle-409104/game-of-thrones-personality-matcher']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'game-of-thrones-servicename', '--image', 'gcr.io/stoked-castle-409104/game-of-thrones-personality-matcher', '--region', 'REGION']
images:
- gcr.io/stoked-castle-409104/game-of-thrones-personality-matcher
