# Define variables for project ID, image name, and tag.
# Customize these values as needed.
substitutions:
  _PROJECT_ID: 'your-gcp-project-id'
  _IMAGE_NAME: 'gcr.io/${_PROJECT_ID}/game-of-thrones-personality-matcher'
  _TAG_NAME: 'latest'
  _REGION: 'us-central1'
  _SERVICE_NAME: 'game-of-thrones-service'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE_NAME}:${_TAG_NAME}', '.']

# Push the Docker image to Google Container Registry.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE_NAME}:${_TAG_NAME}']

# Deploy to Cloud Run.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}'
  - '--image=${_IMAGE_NAME}:${_TAG_NAME}'
  - '--platform=managed'
  - '--region=${_REGION}'
  - '--allow-unauthenticated'

images:
- '${_IMAGE_NAME}:${_TAG_NAME}'
